// DO NOT EDIT
// Generated by JFlex 1.9.1 http://jflex.de/
// source: src/analisis/lexico.jflex

package analisis;

import java_cup.runtime.Symbol;
import excepciones.ControlErrores;
import excepciones.Errores;
import java.util.LinkedList;


@SuppressWarnings("fallthrough")
public class scanner implements java_cup.runtime.Scanner {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0, 0
  };

  /**
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = {
     0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  2,  3,  4,  2,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     1,  5,  6,  0,  0,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 
    18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 19, 20, 21, 22, 23,  0, 
     0, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 33, 36, 37, 
    38, 33, 39, 40, 41, 42, 43, 44, 33, 33, 33, 45, 46, 47, 48, 33, 
     0, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 33, 49, 37, 
    38, 33, 50, 40, 51, 42, 43, 44, 33, 33, 33, 52, 53, 54,  0,  0, 
     0,  0,  0,  0,  0,  3,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0
  };

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\1\1\4\2\1\1\5"+
    "\1\6\1\7\1\10\1\11\1\12\1\13\1\14\1\15"+
    "\1\16\1\17\1\20\1\21\14\22\1\23\1\24\1\25"+
    "\1\26\1\1\1\27\1\30\1\0\1\31\1\0\1\32"+
    "\2\0\1\33\1\34\1\0\1\35\1\36\5\22\1\37"+
    "\3\22\1\40\7\22\1\41\1\42\1\43\10\22\1\44"+
    "\1\45\4\22\1\46\1\22\1\47\1\22\1\50\3\22"+
    "\1\51\4\22\1\52\1\22\1\53\3\22\1\54\1\55"+
    "\2\22\1\56\2\22\1\57\1\60\1\61\1\22\1\62"+
    "\1\63";

  private static int [] zzUnpackAction() {
    int [] result = new int[117];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\67\0\156\0\245\0\334\0\67\0\u0113\0\u014a"+
    "\0\67\0\67\0\u0181\0\67\0\67\0\67\0\u01b8\0\u01ef"+
    "\0\67\0\67\0\u0226\0\67\0\u025d\0\u0294\0\u02cb\0\u0302"+
    "\0\u0339\0\u0370\0\u03a7\0\u03de\0\u0415\0\u044c\0\u0483\0\u04ba"+
    "\0\u04f1\0\67\0\67\0\67\0\67\0\u0528\0\67\0\67"+
    "\0\334\0\67\0\u055f\0\67\0\u0596\0\u05cd\0\67\0\u0604"+
    "\0\u063b\0\67\0\67\0\u0672\0\u06a9\0\u06e0\0\u0717\0\u074e"+
    "\0\u0785\0\u07bc\0\u07f3\0\u082a\0\u0294\0\u0861\0\u0898\0\u08cf"+
    "\0\u0906\0\u093d\0\u0974\0\u09ab\0\67\0\67\0\u063b\0\u09e2"+
    "\0\u0a19\0\u0a50\0\u0a87\0\u0abe\0\u0af5\0\u0b2c\0\u0b63\0\u0294"+
    "\0\u0294\0\u0b9a\0\u0bd1\0\u0c08\0\u0c3f\0\u0294\0\u0c76\0\u0294"+
    "\0\u0cad\0\u0294\0\u0ce4\0\u0d1b\0\u0d52\0\u0294\0\u0d89\0\u0dc0"+
    "\0\u0df7\0\u0e2e\0\u0294\0\u0e65\0\u0294\0\u0e9c\0\u0ed3\0\u0f0a"+
    "\0\u0294\0\u0294\0\u0f41\0\u0f78\0\u0294\0\u0faf\0\u0fe6\0\u0294"+
    "\0\u0294\0\u0294\0\u101d\0\u0294\0\u0294";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[117];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length() - 1;
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpacktrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\2\3\1\0\1\3\1\4\1\5\1\6\1\7"+
    "\1\10\1\11\1\12\1\13\1\14\1\15\1\16\1\2"+
    "\1\17\1\20\1\21\1\22\1\23\1\24\1\25\1\26"+
    "\1\27\1\30\1\31\1\32\1\33\2\26\1\34\5\26"+
    "\1\35\1\26\1\36\1\37\1\26\1\40\1\41\1\42"+
    "\1\2\1\43\1\44\2\26\1\37\1\45\1\46\1\47"+
    "\70\0\2\3\1\0\1\3\110\0\1\50\40\0\2\51"+
    "\1\0\3\51\1\52\47\51\1\53\10\51\10\0\1\54"+
    "\56\0\2\55\1\0\6\55\1\0\44\55\1\56\10\55"+
    "\14\0\1\57\73\0\1\60\65\0\1\61\1\0\1\20"+
    "\72\0\1\62\66\0\1\63\62\0\1\26\5\0\25\26"+
    "\4\0\3\26\25\0\1\26\5\0\15\26\1\64\1\26"+
    "\1\65\5\26\4\0\1\26\1\65\1\26\25\0\1\26"+
    "\5\0\1\66\14\26\1\67\7\26\4\0\3\26\25\0"+
    "\1\26\5\0\4\26\1\70\10\26\1\71\7\26\4\0"+
    "\3\26\25\0\1\26\5\0\13\26\1\72\11\26\4\0"+
    "\3\26\25\0\1\26\5\0\1\73\14\26\1\74\7\26"+
    "\4\0\3\26\25\0\1\26\5\0\5\26\1\75\6\26"+
    "\1\76\10\26\4\0\1\76\2\26\25\0\1\26\5\0"+
    "\17\26\1\77\5\26\4\0\1\26\1\77\1\26\25\0"+
    "\1\26\5\0\21\26\1\100\2\26\1\101\4\0\2\26"+
    "\1\100\25\0\1\26\5\0\17\26\1\102\5\26\4\0"+
    "\1\26\1\102\1\26\25\0\1\26\5\0\1\103\24\26"+
    "\4\0\3\26\25\0\1\26\5\0\7\26\1\104\15\26"+
    "\4\0\3\26\70\0\1\105\7\0\1\51\2\0\1\51"+
    "\44\0\1\51\2\0\3\51\14\0\1\106\63\0\1\55"+
    "\2\0\1\55\44\0\1\55\2\0\3\55\3\0\2\60"+
    "\3\0\62\60\22\0\1\107\66\0\1\26\5\0\15\26"+
    "\1\110\7\26\4\0\3\26\25\0\1\26\5\0\4\26"+
    "\1\111\20\26\4\0\3\26\25\0\1\26\5\0\20\26"+
    "\1\112\4\26\4\0\3\26\25\0\1\26\5\0\14\26"+
    "\1\113\10\26\4\0\1\113\2\26\25\0\1\26\5\0"+
    "\5\26\1\114\17\26\4\0\3\26\25\0\1\26\5\0"+
    "\22\26\1\115\2\26\4\0\3\26\25\0\1\26\5\0"+
    "\20\26\1\116\4\26\4\0\3\26\25\0\1\26\5\0"+
    "\13\26\1\117\11\26\4\0\3\26\25\0\1\26\5\0"+
    "\17\26\1\120\5\26\4\0\1\26\1\120\1\26\25\0"+
    "\1\26\5\0\21\26\1\121\3\26\4\0\2\26\1\121"+
    "\25\0\1\26\5\0\10\26\1\122\14\26\4\0\3\26"+
    "\25\0\1\26\5\0\17\26\1\123\5\26\4\0\1\26"+
    "\1\123\1\26\25\0\1\26\5\0\10\26\1\124\14\26"+
    "\4\0\3\26\25\0\1\26\5\0\22\26\1\125\2\26"+
    "\4\0\3\26\25\0\1\26\5\0\17\26\1\126\5\26"+
    "\4\0\1\26\1\126\1\26\25\0\1\26\5\0\10\26"+
    "\1\127\14\26\4\0\3\26\25\0\1\26\5\0\13\26"+
    "\1\130\11\26\4\0\3\26\25\0\1\26\5\0\1\131"+
    "\24\26\4\0\3\26\25\0\1\26\5\0\4\26\1\132"+
    "\20\26\4\0\3\26\25\0\1\26\5\0\21\26\1\133"+
    "\3\26\4\0\2\26\1\133\25\0\1\26\5\0\1\134"+
    "\24\26\4\0\3\26\25\0\1\26\5\0\1\26\1\135"+
    "\23\26\4\0\3\26\25\0\1\26\5\0\4\26\1\136"+
    "\20\26\4\0\3\26\25\0\1\26\5\0\20\26\1\137"+
    "\4\26\4\0\3\26\25\0\1\26\5\0\14\26\1\140"+
    "\10\26\4\0\1\140\2\26\25\0\1\26\5\0\10\26"+
    "\1\141\14\26\4\0\3\26\25\0\1\26\5\0\21\26"+
    "\1\142\3\26\4\0\2\26\1\142\25\0\1\26\5\0"+
    "\4\26\1\143\20\26\4\0\3\26\25\0\1\26\5\0"+
    "\13\26\1\144\11\26\4\0\3\26\25\0\1\26\5\0"+
    "\12\26\1\145\12\26\4\0\3\26\25\0\1\26\5\0"+
    "\10\26\1\146\14\26\4\0\3\26\25\0\1\26\5\0"+
    "\22\26\1\147\2\26\4\0\3\26\25\0\1\26\5\0"+
    "\13\26\1\150\11\26\4\0\3\26\25\0\1\26\5\0"+
    "\4\26\1\151\20\26\4\0\3\26\25\0\1\26\5\0"+
    "\21\26\1\152\3\26\4\0\2\26\1\152\25\0\1\26"+
    "\5\0\14\26\1\153\10\26\4\0\1\153\2\26\25\0"+
    "\1\26\5\0\2\26\1\154\22\26\4\0\3\26\25\0"+
    "\1\26\5\0\4\26\1\155\20\26\4\0\3\26\25\0"+
    "\1\26\5\0\14\26\1\156\10\26\4\0\1\156\2\26"+
    "\25\0\1\26\5\0\13\26\1\157\11\26\4\0\3\26"+
    "\25\0\1\26\5\0\4\26\1\160\20\26\4\0\3\26"+
    "\25\0\1\26\5\0\6\26\1\161\16\26\4\0\3\26"+
    "\25\0\1\26\5\0\7\26\1\162\15\26\4\0\3\26"+
    "\25\0\1\26\5\0\22\26\1\163\2\26\4\0\3\26"+
    "\25\0\1\26\5\0\21\26\1\164\3\26\4\0\2\26"+
    "\1\164\25\0\1\26\5\0\4\26\1\165\20\26\4\0"+
    "\3\26\3\0";

  private static int [] zzUnpacktrans() {
    int [] result = new int[4180];
    int offset = 0;
    offset = zzUnpacktrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpacktrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\3\1\1\11\2\1\2\11\1\1\3\11"+
    "\2\1\2\11\1\1\1\11\15\1\4\11\1\1\2\11"+
    "\1\0\1\11\1\0\1\11\2\0\1\11\1\1\1\0"+
    "\2\11\21\1\2\11\57\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[117];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen())];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  private boolean zzEOFDone;

  /* user code: */

    // lista global de tokens del scanner
    public static LinkedList<Token> listaTokens = new LinkedList<>();

    private void agregarToken(String tipo) {
        listaTokens.add(new Token(tipo, yytext(), yyline, yycolumn));
    }

        private String unescape(String s) {
        StringBuilder out = new StringBuilder();
        for (int i = 0; i < s.length(); i++) {
            char c = s.charAt(i);
            if (c == '\\' && i + 1 < s.length()) {
                char n = s.charAt(i + 1);
                switch (n) {
                    case 'n': out.append('\n'); i++; break;
                    case 't': out.append('\t'); i++; break;
                    case 'r': out.append('\r'); i++; break;
                    case '\\': out.append('\\'); i++; break;
                    case '"': out.append('\"'); i++; break;
                    case '\'': out.append('\''); i++; break;
                    default:
                        // si no es escape válido, deja el '\'
                        out.append(c);
                        break;
                }
            } else {
                out.append(c);
            }
        }
        return out.toString();
    }




  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public scanner(java.io.Reader in) {
      yyline = 1;
    yycolumn = 1;
    this.zzReader = in;
  }


  /** Returns the maximum size of the scanner buffer, which limits the size of tokens. */
  private int zzMaxBufferLen() {
    return Integer.MAX_VALUE;
  }

  /**  Whether the scanner buffer can grow to accommodate a larger token. */
  private boolean zzCanGrow() {
    return true;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    return ZZ_CMAP[input];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate && zzCanGrow()) {
      /* if not, and it can grow: blow it up */
      char newBuffer[] = new char[Math.min(zzBuffer.length * 2, zzMaxBufferLen())];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      if (requested == 0) {
        throw new java.io.EOFException("Scan buffer limit reached ["+zzBuffer.length+"]");
      }
      else {
        throw new java.io.IOException(
            "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
      }
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    int initBufferSize = Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen());
    if (zzBuffer.length > initBufferSize) {
      zzBuffer = new char[initBufferSize];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
  yyclose();    }
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  @Override  public java_cup.runtime.Symbol next_token() throws java.io.IOException
  {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      yychar+= zzMarkedPosL-zzStartRead;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { return new java_cup.runtime.Symbol(sym.EOF); }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { String desc = "Símbolo no reconocido: " + yytext();
    System.out.println("Error Léxico: " + desc +
                       " | Fila:" + yyline +
                       " | Columna:" + yycolumn);

    Errores err = new Errores("LEXICO", desc, yyline, yycolumn);
    ControlErrores.agregarError(err);
            }
          // fall through
          case 52: break;
          case 2:
            { /* ignorar espacios */
            }
          // fall through
          case 53: break;
          case 3:
            { agregarToken("NOT"); return new Symbol(sym.NOT, yyline, yycolumn, yytext());
            }
          // fall through
          case 54: break;
          case 4:
            { agregarToken("MOD");   return new Symbol(sym.MOD,   yyline, yycolumn, yytext());
            }
          // fall through
          case 55: break;
          case 5:
            { agregarToken("PAR1");      return new Symbol(sym.PAR1,      yyline, yycolumn, yytext());
            }
          // fall through
          case 56: break;
          case 6:
            { agregarToken("PAR2");      return new Symbol(sym.PAR2,      yyline, yycolumn, yytext());
            }
          // fall through
          case 57: break;
          case 7:
            { agregarToken("POR");   return new Symbol(sym.POR,   yyline, yycolumn, yytext());
            }
          // fall through
          case 58: break;
          case 8:
            { agregarToken("MAS");   return new Symbol(sym.MAS,   yyline, yycolumn, yytext());
            }
          // fall through
          case 59: break;
          case 9:
            { agregarToken("COMA");      return new Symbol(sym.COMA,      yyline, yycolumn, yytext());
            }
          // fall through
          case 60: break;
          case 10:
            { agregarToken("MENOS"); return new Symbol(sym.MENOS, yyline, yycolumn, yytext());
            }
          // fall through
          case 61: break;
          case 11:
            { agregarToken("DIV");   return new Symbol(sym.DIV,   yyline, yycolumn, yytext());
            }
          // fall through
          case 62: break;
          case 12:
            { agregarToken("ENTERO");  return new Symbol(sym.ENTERO,  yyline, yycolumn, yytext());
            }
          // fall through
          case 63: break;
          case 13:
            { agregarToken("DOSPUNTOS"); return new Symbol(sym.DOSPUNTOS, yyline, yycolumn, yytext());
            }
          // fall through
          case 64: break;
          case 14:
            { agregarToken("FINCADENA"); return new Symbol(sym.FINCADENA, yyline, yycolumn, yytext());
            }
          // fall through
          case 65: break;
          case 15:
            { agregarToken("MENORQ");     return new Symbol(sym.MENORQ,     yyline, yycolumn, yytext());
            }
          // fall through
          case 66: break;
          case 16:
            { agregarToken("IGUAL");     return new Symbol(sym.IGUAL,     yyline, yycolumn, yytext());
            }
          // fall through
          case 67: break;
          case 17:
            { agregarToken("MAYORQ");     return new Symbol(sym.MAYORQ,     yyline, yycolumn, yytext());
            }
          // fall through
          case 68: break;
          case 18:
            { agregarToken("ID");      return new Symbol(sym.ID,      yyline, yycolumn, yytext());
            }
          // fall through
          case 69: break;
          case 19:
            { agregarToken("CORCHIZQ");  return new Symbol(sym.CORCHIZQ,  yyline, yycolumn, yytext());
            }
          // fall through
          case 70: break;
          case 20:
            { agregarToken("CORCHDER");  return new Symbol(sym.CORCHDER,  yyline, yycolumn, yytext());
            }
          // fall through
          case 71: break;
          case 21:
            { agregarToken("XOR"); return new Symbol(sym.XOR, yyline, yycolumn, yytext());
            }
          // fall through
          case 72: break;
          case 22:
            { agregarToken("LLAVEIZQ");  return new Symbol(sym.LLAVEIZQ,  yyline, yycolumn, yytext());
            }
          // fall through
          case 73: break;
          case 23:
            { agregarToken("LLAVEDER");  return new Symbol(sym.LLAVEDER,  yyline, yycolumn, yytext());
            }
          // fall through
          case 74: break;
          case 24:
            { agregarToken("DIFERENTE");  return new Symbol(sym.DIFERENTE,  yyline, yycolumn, yytext());
            }
          // fall through
          case 75: break;
          case 25:
            { String raw = yytext(); // incluye comillas dobles
    String contenido = raw.substring(1, raw.length() - 1); // sin " "
    String val = unescape(contenido);

    agregarToken("CADENA");
    return new Symbol(sym.CADENA, yyline, yycolumn, val);
            }
          // fall through
          case 76: break;
          case 26:
            { agregarToken("AND"); return new Symbol(sym.AND, yyline, yycolumn, yytext());
            }
          // fall through
          case 77: break;
          case 27:
            { agregarToken("POT");   return new Symbol(sym.POT,   yyline, yycolumn, yytext());
            }
          // fall through
          case 78: break;
          case 28:
            { /* ignorar comentario de línea */
            }
          // fall through
          case 79: break;
          case 29:
            { agregarToken("MENORIGUAL"); return new Symbol(sym.MENORIGUAL, yyline, yycolumn, yytext());
            }
          // fall through
          case 80: break;
          case 30:
            { agregarToken("MAYORIGUAL"); return new Symbol(sym.MAYORIGUAL, yyline, yycolumn, yytext());
            }
          // fall through
          case 81: break;
          case 31:
            { agregarToken("DO");      return new Symbol(sym.DO,      yyline, yycolumn, yytext());
            }
          // fall through
          case 82: break;
          case 32:
            { agregarToken("IF");      return new Symbol(sym.IF,      yyline, yycolumn, yytext());
            }
          // fall through
          case 83: break;
          case 33:
            { agregarToken("OR");  return new Symbol(sym.OR,  yyline, yycolumn, yytext());
            }
          // fall through
          case 84: break;
          case 34:
            { String raw = yytext(); // incluye comillas simples
    String contenido = raw.substring(1, raw.length() - 1); // sin ' '
    String val = unescape(contenido);

    agregarToken("CHAR");
    return new Symbol(sym.CHAR, yyline, yycolumn, val.charAt(0));
            }
          // fall through
          case 85: break;
          case 35:
            { agregarToken("DECIMAL"); return new Symbol(sym.DECIMAL, yyline, yycolumn, yytext());
            }
          // fall through
          case 86: break;
          case 36:
            { agregarToken("FOR");     return new Symbol(sym._for,    yyline, yycolumn, yytext());
            }
          // fall through
          case 87: break;
          case 37:
            { agregarToken("INT");     return new Symbol(sym.INT,     yyline, yycolumn, yytext());
            }
          // fall through
          case 88: break;
          case 38:
            { agregarToken("VAR");     return new Symbol(sym.VAR,     yyline, yycolumn, yytext());
            }
          // fall through
          case 89: break;
          case 39:
            { agregarToken("BOOL");    return new Symbol(sym.BOOL,    yyline, yycolumn, yytext());
            }
          // fall through
          case 90: break;
          case 40:
            { agregarToken("CASE");    return new Symbol(sym.CASE,    yyline, yycolumn, yytext());
            }
          // fall through
          case 91: break;
          case 41:
            { agregarToken("ELSE");    return new Symbol(sym.ELSE,    yyline, yycolumn, yytext());
            }
          // fall through
          case 92: break;
          case 42:
            { agregarToken("TRUE");    return new Symbol(sym.TRUE,    yyline, yycolumn, yytext());
            }
          // fall through
          case 93: break;
          case 43:
            { agregarToken("BREAK");   return new Symbol(sym._break,  yyline, yycolumn, yytext());
            }
          // fall through
          case 94: break;
          case 44:
            { agregarToken("FALSE");   return new Symbol(sym.FALSE,   yyline, yycolumn, yytext());
            }
          // fall through
          case 95: break;
          case 45:
            { agregarToken("PRINT");   return new Symbol(sym.PRINT,   yyline, yycolumn, yytext());
            }
          // fall through
          case 96: break;
          case 46:
            { agregarToken("WHILE");   return new Symbol(sym._while,  yyline, yycolumn, yytext());
            }
          // fall through
          case 97: break;
          case 47:
            { agregarToken("DOUBLE");  return new Symbol(sym.DOUBLE,  yyline, yycolumn, yytext());
            }
          // fall through
          case 98: break;
          case 48:
            { agregarToken("STRING");  return new Symbol(sym.STRING,  yyline, yycolumn, yytext());
            }
          // fall through
          case 99: break;
          case 49:
            { agregarToken("SWITCH");  return new Symbol(sym.SWITCH,  yyline, yycolumn, yytext());
            }
          // fall through
          case 100: break;
          case 50:
            { agregarToken("DEFAULT"); return new Symbol(sym.DEFAULT, yyline, yycolumn, yytext());
            }
          // fall through
          case 101: break;
          case 51:
            { agregarToken("CONTINUE"); return new Symbol(sym._continue, yyline, yycolumn, yytext());
            }
          // fall through
          case 102: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
