
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analisis;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MOD = 14;
  public static final int MENOS = 11;
  public static final int CADENA = 2;
  public static final int MENORIGUAL = 19;
  public static final int IGUAL = 16;
  public static final int CHAR = 5;
  public static final int FINCADENA = 6;
  public static final int DECIMAL = 4;
  public static final int TRUE = 23;
  public static final int MENORQ = 18;
  public static final int UMENOS = 15;
  public static final int POR = 12;
  public static final int EQUALS = 17;
  public static final int MAYORQ = 20;
  public static final int EOF = 0;
  public static final int DIFERENTE = 22;
  public static final int DIV = 13;
  public static final int MAYORIGUAL = 21;
  public static final int FALSE = 24;
  public static final int PRINT = 7;
  public static final int error = 1;
  public static final int PAR2 = 9;
  public static final int PAR1 = 8;
  public static final int ENTERO = 3;
  public static final int MAS = 10;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "CADENA",
  "ENTERO",
  "DECIMAL",
  "CHAR",
  "FINCADENA",
  "PRINT",
  "PAR1",
  "PAR2",
  "MAS",
  "MENOS",
  "POR",
  "DIV",
  "MOD",
  "UMENOS",
  "IGUAL",
  "EQUALS",
  "MENORQ",
  "MENORIGUAL",
  "MAYORQ",
  "MAYORIGUAL",
  "DIFERENTE",
  "TRUE",
  "FALSE"
  };
}

